extends Node

# Attach as a child of a level's NavigationRegion2D. On _ready, scans the
# level's TileMap "Solid" layer for ledges (a solid cell with open air above
# it — i.e. a standing surface) and auto-inserts NavigationLink2D bridges
# between ledges that are close enough to jump between, using generic
# "can an enemy jump this" arc math (see can_reach_gap below, mirrors
# EnemyLocomotion.can_reach_gap so the same formula backs both link
# generation and the per-enemy jump decision).
#
# This is what lets levels be built for platforming without also hand-laying
# a separate ground-only path for enemies to patrol/chase on: any gap within
# the reach envelope below gets a link, and any enemy generating a
# NavigationAgent2D path through this NavigationRegion2D can route across it.
#
# Deliberately reads the ALREADY-BAKED TileMap cell data rather than parsing
# NavigationPolygon geometry directly — the tilemap's Solid layer is a
# simpler, more reliable source of "which cells are ledges" than reverse-
# engineering polygon outlines, and every level already has one.

@export var solid_layer_name: String = "Solid"
@export var min_gap_tiles: float = 1.5  # skip trivially-close cells (would already connect via the baked navmesh itself)
@export var max_gap_tiles: float = 8.0  # hard ceiling so a level-spanning "link" never gets generated by accident
@export var jump_velocity: float = -420.0
@export var gravity: float = 1200.0
@export var approach_speed: float = 150.0

var _generated_links: Array[NavigationLink2D] = []


func _ready() -> void:
	call_deferred("_generate_links")


func _generate_links() -> void:
	var tile_map := _find_tilemap()
	if tile_map == null:
		return

	var layer_idx := _find_layer(tile_map, solid_layer_name)
	if layer_idx < 0:
		push_warning("NavLinkGenerator: no TileMap layer named '%s' found — skipping." % solid_layer_name)
		return

	var tile_size: Vector2 = Vector2(tile_map.tile_set.tile_size)
	var solid_cells: Dictionary = {}  # Vector2i -> true, for O(1) neighbor checks
	for cell in tile_map.get_used_cells(layer_idx):
		solid_cells[cell] = true

	var runs := _find_ledge_runs(solid_cells)
	if runs.size() < 2:
		return

	var region: Node2D = get_parent()
	var links_made := 0
	for i in range(runs.size()):
		for j in range(i + 1, runs.size()):
			if _try_link_runs(runs[i], runs[j], tile_map, tile_size, region):
				links_made += 1

	if links_made > 0:
		print("NavLinkGenerator: generated %d jump link(s) for %s." % [links_made, tile_map.get_path()])


func _find_tilemap() -> TileMap:
	var scene := get_tree().current_scene
	if scene == null:
		return null
	return _find_tilemap_recursive(scene)


func _find_tilemap_recursive(node: Node) -> TileMap:
	if node is TileMap:
		return node
	for child in node.get_children():
		var found := _find_tilemap_recursive(child)
		if found != null:
			return found
	return null


func _find_layer(tile_map: TileMap, layer_name: String) -> int:
	for i in range(tile_map.get_layers_count()):
		if tile_map.get_layer_name(i) == layer_name:
			return i
	return -1


# A "ledge" cell is solid with no solid cell directly above it — the top
# surface a character would actually stand on. Contiguous ledge cells at the
# same row get grouped into one run (a platform's walkable top).
func _find_ledge_runs(solid_cells: Dictionary) -> Array:
	var ledge_cells: Array[Vector2i] = []
	for cell in solid_cells.keys():
		var above := Vector2i(cell.x, cell.y - 1)
		if not solid_cells.has(above):
			ledge_cells.append(cell)

	ledge_cells.sort_custom(func(a, b): return a.y < b.y if a.y != b.y else a.x < b.x)

	var runs := []
	var current_run := []
	for cell in ledge_cells:
		if current_run.is_empty() or (cell.y == current_run[-1].y and cell.x == current_run[-1].x + 1):
			current_run.append(cell)
		else:
			runs.append(current_run)
			current_run = [cell]
	if not current_run.is_empty():
		runs.append(current_run)
	return runs


func _try_link_runs(run_a: Array, run_b: Array, tile_map: TileMap, tile_size: Vector2, region: Node2D) -> bool:
	# Nearest endpoint pair between the two runs (each run is a contiguous
	# horizontal strip, so only the two ends of each ever matter).
	var candidates_a = [run_a[0], run_a[-1]]
	var candidates_b = [run_b[0], run_b[-1]]

	var best_dist := INF
	var best_a: Vector2i
	var best_b: Vector2i
	for a in candidates_a:
		for b in candidates_b:
			var d = absf(float(a.x - b.x))
			if d < best_dist:
				best_dist = d
				best_a = a
				best_b = b

	var gap_tiles: float = best_dist
	if gap_tiles < min_gap_tiles or gap_tiles > max_gap_tiles:
		return false

	var world_a: Vector2 = tile_map.to_global(tile_map.map_to_local(best_a)) + Vector2(0, -tile_size.y * 0.5)
	var world_b: Vector2 = tile_map.to_global(tile_map.map_to_local(best_b)) + Vector2(0, -tile_size.y * 0.5)

	var horizontal_gap: float = absf(world_b.x - world_a.x)
	var vertical_delta: float = world_b.y - world_a.y  # positive = b is lower than a

	# Try both directions — a gap reachable jumping A->B isn't necessarily
	# reachable B->A if the ledges are at different heights.
	var a_to_b := can_reach_gap(horizontal_gap, vertical_delta)
	var b_to_a := can_reach_gap(horizontal_gap, -vertical_delta)
	if not a_to_b and not b_to_a:
		return false

	var link := NavigationLink2D.new()
	link.start_position = region.to_local(world_a)
	link.end_position = region.to_local(world_b)
	link.bidirectional = a_to_b and b_to_a
	link.enabled = true
	region.add_child(link)
	_generated_links.append(link)
	return true


func can_reach_gap(horizontal_gap: float, vertical_delta: float) -> bool:
	var discriminant: float = jump_velocity * jump_velocity + 2.0 * gravity * vertical_delta
	if discriminant < 0.0:
		return false
	var t: float = (-jump_velocity + sqrt(discriminant)) / gravity
	if t <= 0.0:
		return false
	return approach_speed * t >= horizontal_gap
